# Prometheus configuration for Earnings Gap Trading System
global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    cluster: 'earnings-gap-trader'
    environment: 'production'

# Rule files for alerting
rule_files:
  - "alerts/*.yml"

# Alertmanager configuration
alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093

# Scrape configurations
scrape_configs:
  # Main application metrics
  - job_name: 'earnings-gap-trader'
    static_configs:
      - targets: ['app:9000']
    scrape_interval: 5s
    metrics_path: /metrics
    params:
      format: ['prometheus']
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: app:9000

  # Health monitoring service
  - job_name: 'health-monitor'
    static_configs:
      - targets: ['health-monitor:9001']
    scrape_interval: 10s
    metrics_path: /metrics

  # PostgreSQL database metrics
  - job_name: 'postgres-exporter'
    static_configs:
      - targets: ['postgres-exporter:9187']
    scrape_interval: 30s

  # Redis metrics
  - job_name: 'redis-exporter'
    static_configs:
      - targets: ['redis-exporter:9121']
    scrape_interval: 30s

  # Node metrics (system resources)
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']
    scrape_interval: 15s

  # Nginx metrics
  - job_name: 'nginx-exporter'
    static_configs:
      - targets: ['nginx-exporter:9113']
    scrape_interval: 30s

  # RabbitMQ metrics
  - job_name: 'rabbitmq-exporter'
    static_configs:
      - targets: ['rabbitmq-exporter:9419']
    scrape_interval: 30s

  # Celery worker metrics
  - job_name: 'celery-exporter'
    static_configs:
      - targets: ['celery-exporter:9540']
    scrape_interval: 15s

  # Trading API metrics (custom endpoint)
  - job_name: 'trading-api-metrics'
    static_configs:
      - targets: ['app:8000']
    scrape_interval: 5s
    metrics_path: /api/metrics
    scheme: http

  # External service monitoring
  - job_name: 'external-services'
    http_sd_configs:
      - url: http://app:8000/api/monitoring/targets
        refresh_interval: 60s
    scrape_interval: 30s
    scrape_timeout: 10s

  # BlackBox exporter for endpoint monitoring
  - job_name: 'blackbox'
    metrics_path: /probe
    params:
      module: [http_2xx]
    static_configs:
      - targets:
        - http://app:8000/health
        - http://app:8000/api/status
        - https://api.kite.zerodha.com
        - https://api.telegram.org
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackbox-exporter:9115

# Remote write configuration (for long-term storage)
remote_write:
  - url: "http://victoria-metrics:8428/api/v1/write"
    queue_config:
      max_samples_per_send: 10000
      batch_send_deadline: 5s
      min_shards: 1
      max_shards: 200

# Storage configuration
storage:
  tsdb:
    path: /prometheus/data
    retention.time: 15d
    retention.size: 10GB
    wal-compression: true

# Performance tuning
scrape_timeout: 10s
query_timeout: 2m
max_concurrent_queries: 20

# Service discovery configurations
consul_sd_configs:
  - server: 'consul:8500'
    services: ['earnings-gap-trader', 'trading-services']
    refresh_interval: 30s